Promises are shown here . 
Promises are made to resolve call back hell 

Promises usually identify two things resolve and reject

Resolve -- When there is no error in the function call it can easily return the required output to it

Reject -- When there is an unexpected catch or an error while executing a function the promise func will not stop executing rather it shows that the promise is rejected hence not affecting the later function calls


Here I have created a promise which will resolve on a random no and reject on a random no